// Generated by CoffeeScript 1.6.3
(function() {
  var compile, fs;

  compile = require('coffee-script').compile;

  fs = require('fs');

  module.exports.makefile = function(file, cb) {
    fs.readFile(__dirname + '/coffee/' + file + '.coffee', 'utf8', function(err, data) {
      cb(compile(data));
    });
  };

  module.exports.middleware = function(source) {
    var fn;
    return fn = function(req, res, next) {
      var file;
      console.log(req);
      file = req.params.file.split('.')[0];
      return builder.makefile(file, function(data) {
        return res.send(data);
      });
    };
  };

}).call(this);
