// Generated by CoffeeScript 1.6.3
(function() {
  var compile, fs;

  compile = require('coffee-script').compile;

  fs = require('fs');

  module.exports.makefile = function(file, source, cb) {
    console.log(source + '/' + file + '.coffee');
    fs.readFile(source + '/' + file + '.coffee', 'utf8', function(err, data) {
      cb(compile(data));
    });
  };

  module.exports.middleware = function(source) {
    var fn;
    console.log(source);
    return fn = function(req, res, next) {
      var extention, file, path;
      path = req.url.split('/');
      file = path[path.length - 1].split('.');
      extention = file[1];
      if (extention === 'js') {
        return module.exports.makefile(file[0], source, function(data) {
          return res.send(data);
        });
      }
    };
  };

}).call(this);
