// Generated by CoffeeScript 1.6.3
(function() {
  var compile, fs;

  compile = require('coffee-script').compile;

  fs = require('fs');

  module.exports.makefile = function(file, source, cb) {
    fs.readFile(source + '/' + file + '.coffee', 'utf8', function(err, data) {
      cb(compile(data));
    });
  };

  module.exports.middleware = function(source) {
    var fn;
    return fn = function(req, res, next) {
      var extention, file, path;
      path = req.url.split('/');
      file = path[path.length - 1];
      extention = file[1];
      if (extention = 'js') {
        return builder.makefile(file[0], source, function(data) {
          return res.send(data);
        });
      }
    };
  };

}).call(this);
